export const mockProducts = [
  {
    id: '1',
    name: 'Coca-Cola 350ml',
    price: 3.50,
    stock: 50,
    min_stock: 10,
    barcode: '123456789',
    image_url: 'https://images.pexels.com/photos/50593/coca-cola-cold-drink-soft-drink-coke-50593.jpeg?auto=compress&cs=tinysrgb&w=400',
    type: 'product',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '2',
    name: 'Pão de Açúcar',
    price: 0.50,
    stock: 100,
    min_stock: 20,
    type: 'product',
    image_url: 'https://images.pexels.com/photos/209206/pexels-photo-209206.jpeg?auto=compress&cs=tinysrgb&w=400',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '3',
    name: 'Leite Integral 1L',
    price: 4.80,
    stock: 5,
    min_stock: 15,
    type: 'product',
    image_url: 'https://images.pexels.com/photos/416354/pexels-photo-416354.jpeg?auto=compress&cs=tinysrgb&w=400',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '4',
    name: 'Sabonete Líquido',
    price: 8.90,
    stock: 0,
    min_stock: 5,
    type: 'product',
    image_url: 'https://images.pexels.com/photos/4465831/pexels-photo-4465831.jpeg?auto=compress&cs=tinysrgb&w=400',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '5',
    name: 'Corte de Cabelo',
    price: 35.00,
    stock: 0,
    min_stock: 0,
    type: 'service',
    description: 'Corte de cabelo tradicional',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '6',
    name: 'Manicure',
    price: 25.00,
    stock: 0,
    min_stock: 0,
    type: 'service',
    description: 'Serviço de manicure completo',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
];

export const mockCustomers = [
  {
    id: '1',
    name: 'João Silva',
    phone: '(11) 98765-4321',
    email: 'joao.silva@email.com',
    whatsapp: 1,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '2',
    name: 'Maria Santos',
    phone: '(11) 91234-5678',
    email: 'maria.santos@email.com',
    whatsapp: 1,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '3',
    name: 'Pedro Costa',
    phone: '(11) 99988-7766',
    email: 'pedro.costa@email.com',
    whatsapp: 1,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '4',
    name: 'Ana Oliveira',
    phone: '(11) 95544-3322',
    email: 'ana.oliveira@email.com',
    whatsapp: 0,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
];

export const mockSales = [
  {
    id: '1',
    customer_id: '1',
    customer_name: 'João Silva',
    total: 14.30,
    payment_method: 'Dinheiro',
    observation: '',
    created_at: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    items: [
      { product_id: '1', product_name: 'Coca-Cola 350ml', quantity: 2, unit_price: 3.50, total: 7.00 },
      { product_id: '2', product_name: 'Pão de Açúcar', quantity: 10, unit_price: 0.50, total: 5.00 },
      { product_id: '3', product_name: 'Leite Integral 1L', quantity: 1, unit_price: 4.80, total: 4.80 },
    ],
  },
  {
    id: '2',
    customer_id: '2',
    customer_name: 'Maria Santos',
    total: 35.00,
    payment_method: 'PIX',
    observation: 'Pagamento via PIX',
    created_at: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
    items: [
      { product_id: '5', product_name: 'Corte de Cabelo', quantity: 1, unit_price: 35.00, total: 35.00 },
    ],
  },
  {
    id: '3',
    customer_id: '3',
    customer_name: 'Pedro Costa',
    total: 17.80,
    payment_method: 'Cartão',
    observation: '',
    created_at: new Date().toISOString(),
    items: [
      { product_id: '4', product_name: 'Sabonete Líquido', quantity: 2, unit_price: 8.90, total: 17.80 },
    ],
  },
];

export const mockExpenses = [
  {
    id: '1',
    name: 'Aluguel',
    amount: 2500.00,
    due_date: new Date(2025, 9, 10).toISOString(),
    paid: 1,
    recurring: 1,
    customer_id: null,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '2',
    name: 'Energia Elétrica',
    amount: 450.00,
    due_date: new Date(2025, 9, 15).toISOString(),
    paid: 0,
    recurring: 1,
    customer_id: null,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '3',
    name: 'Fornecedor - Produtos',
    amount: 3200.00,
    due_date: new Date(2025, 9, 20).toISOString(),
    paid: 0,
    recurring: 0,
    customer_id: null,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '4',
    name: 'Serviço de Limpeza',
    amount: 150.00,
    due_date: new Date(2025, 9, 25).toISOString(),
    paid: 0,
    recurring: 0,
    customer_id: '1', // João Silva
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '5',
    name: 'Manutenção de Equipamentos',
    amount: 300.00,
    due_date: new Date(2025, 9, 30).toISOString(),
    paid: 0,
    recurring: 0,
    customer_id: '2', // Maria Santos
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '4',
    name: 'Salário Funcionário',
    amount: 1800.00,
    due_date: new Date(2025, 9, 5).toISOString(),
    paid: 1,
    recurring: 1,
    customer_id: null,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '5',
    name: 'Compra fiado - João Silva',
    amount: 150.00,
    due_date: new Date(2025, 9, 25).toISOString(),
    paid: 0,
    recurring: 0,
    customer_id: '1',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '6',
    name: 'Compra fiado - João Silva',
    amount: 85.50,
    due_date: new Date(2025, 9, 28).toISOString(),
    paid: 0,
    recurring: 0,
    customer_id: '1',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '7',
    name: 'Compra fiado - Maria Santos',
    amount: 220.00,
    due_date: new Date(2025, 9, 22).toISOString(),
    paid: 0,
    recurring: 0,
    customer_id: '2',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
];
